version: "3.8"

services:
    client:
        build:
            context: ./client
        ports:
            - "3000:80"
        depends_on:
            - server
        environment:
            - VITE_API=http://server:3001/api/

    server:
        build:
            context: ./server
        ports:
            - "3001:3005"
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=testdb
            - PORT=3005
        depends_on:
            - db

    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: testdb
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    pgdata:
